### ISSUE TITLE
RPC Docs menu item cause page shift

### ISSUE THREAD

**Issue by wintercooled** [ElementsProject/elementsproject.github.io#121]
When you select RPC Docs the page content shifts.

I think this is because it uses a different div (class page and not class post). But this is also probably related to the index files being .html but containing markdown and not .md files.

**Comment by stevenroose** [comment]
Are you sure this is not because the scroll bar disappears? Try shifting between Community and RPC Docs. Nothing shifts for me.

**Comment by wintercooled** [comment]
Oh yes - that's annoying. If I add extra content to extend the page so it has a sidebar it doesn't happen.
