### ISSUE TITLE
features/confidential-transactions shows values for CT_BITS=32, but now CT_BITS is 52

### ISSUE THREAD

**Issue by dgpv** [ElementsProject/elementsproject.github.io#126]
https://github.com/ElementsProject/elementsproject.github.io/blame/master/features/confidential-transactions/index.md#L93-L95

The values in the referenced lines refer to old parameters, now (after https://github.com/ElementsProject/elements/pull/834 was merged) CT_BITS allow to cover the whole range of 21M expressible on Bitcoin. Also, as I understand, `min_value` for a long time was 1, allowing to blind values from 1 satoshi (https://github.com/ElementsProject/elements/blob/95602ec21f0b3ec4a58f36bbc1c53bb757c97701/src/blind.cpp#L184)

**Comment by dgpv** [comment]
I think referring to the current parameters could prevent confusion for the readers, as there is now a real-world system with concrete parameters, and readers might assume that the parameters listed on this page apply to that system.

**Comment by wintercooled** [comment]
Thanks @dgpv - I will edit and get review shortly.

**Comment by wintercooled** [comment]
https://github.com/ElementsProject/elementsproject.github.io/pull/127/files

**Comment by wintercooled** [comment]
Closed with #127
