### ISSUE TITLE
Elements-qt title correction of network name (v21.99.0)

### ISSUE THREAD

**Issue by andreabonel** [ElementsProject/elementsproject.github.io#162]
little bug in title in v21.99.0:
![Screenshot elements-qt with both different network names](https://user-images.githubusercontent.com/94554885/179566296-ac1a56c2-79e3-4131-84fe-81e442192f03.png)

in v0.21.0.2 it was ok: 
![Screenshot elements-qt 0 21 0 2](https://user-images.githubusercontent.com/94554885/179568058-ba9eea2c-0ac1-4157-98e0-1a25014d03e6.png)

**Comment by wintercooled** [comment]
Is this not an issue with elements core itself?

**Comment by andreabonel** [comment]
wrong repo
