### ISSUE TITLE
Spendable coins and "Anyone can spend"

### ISSUE THREAD

**Issue by adiack** [ElementsProject/elementsproject.github.io#28]
On elements tutorial: Basic operations

Explanation on "Anyone-can-spend" was great, especially for users who have not done bitcoin script..
However paragrah below is not so clear to me:

_Let’s drain the “anyone-can-spend” values and send half the assets to a new address generated by each Elements node. We’ll also need to generate more than 100 blocks so that the coins are spendable (a requirement of the maturity rule for spending coinbase rewards):_

Any reason for picking 100 blocks and not 1 block?
What is "the maturity rule for spending coinbase rewards" referring to?

**Comment by instagibbs** [comment]
Based on Bitcoin outputs in coinbase transactions can not be spent until
they mature 100 blocks. This isn't strictly necessary for Elements signed
blockchains but was left in for maximum compatibility.

**Comment by wintercooled** [comment]
I will add that to the page for clarity @instagibbs . Thanks for asking @adiack

**Comment by wintercooled** [comment]
I guess 'coinbase' should also just be 'fees collected' as well....
