### ISSUE TITLE
TLS Certificate invalid: www.elementsproject.org

### ISSUE THREAD

**Issue by jonathancross** [ElementsProject/elementsproject.github.io#50]
The current Let's Encrypt TLS certificate for `www.elementsproject.org` is issued to `www.blockstream.com` and is throwing errors in Chrome, Safari, `curl` and presumably other browsers.  Tested on macOS.
```
curl -v https://www.elementsproject.org/
*   Trying 35.193.30.29...
* Connected to www.elementsproject.org (35.193.30.29) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /opt/local/share/curl/curl-ca-bundle.crt
  CApath: none
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
* 	 subject: CN=www.blockstream.com
* 	 start date: 2018-12-01 19:00:10 GMT
* 	 expire date: 2019-03-01 19:00:10 GMT
* 	 subjectAltName does not match www.elementsproject.org
* SSL: no alternative certificate subject name matches target host name 'www.elementsproject.org'
* Closing connection 0
* TLSv1.2 (OUT), TLS alert, Client hello (1):
curl: (51) SSL: no alternative certificate subject name matches target host name 'www.elementsproject.org'
```

https://www.elementsproject.org - invalid certificate for `www.blockstream.com`.

Serial Number: `03 B2 9A FE 11 E9 0C 25 09 41 BA CF 68 D7 09 50 83 2A`

https://elementsproject.org - valid cert

Serial Number: `03 78 2B 25 D1 DC 36 E6 4C FA DA 0C 6B CA 05 C8 79 C1`

**Comment by jonathancross** [comment]
NOTE: If I search for `p2ep blockstream elements`: https://duckduckgo.com/?q=p2ep+blockstream+elements&ia=web

I get this link: https://www.elementsproject.org/2018/08/08/improving-privacy-using-pay-to-endpoint/

Which is broken because of the certificate.

But, if I change the domain to `www.blockstream.com` - the page loads correctly:
https://www.blockstream.com/2018/08/08/improving-privacy-using-pay-to-endpoint/

Something also seems to be misconfigured in SEO and/or redirects.

**Comment by wintercooled** [comment]
Thanks for the details @jonathancross - will look into this now.

**Comment by wintercooled** [comment]
The source of the issue has been fixed. https://www.elementsproject.org will forward correctly now.

The existing search engine results will, I assume, update at some point when they next crawl relevant content. I will leave this open a day or two to make sure that the fix isn't changed in anyway by time related refreshes of DNS etc.
