### ISSUE TITLE
Improve your domain

### ISSUE THREAD

**Issue by tmaierACN** [ElementsProject/elementsproject.github.io#7]
Hi,

i just came by your webpage and saw that http://blockstream.com redirects directly to https://github.com/ElementsProject/elementsproject.github.io
instead of http://www.blockstream.com.

You are using cloudflare? Maybe this post helps: https://support.cloudflare.com/hc/en-us/articles/200172286-How-do-I-perform-URL-forwarding-or-redirects-with-CloudFlare-

Besides this, I would add the URL http://www.blockstream.com to the repository description here on github.

**Comment by martindale** [comment]
With the new ElementsProject.org, this should now be resolved.
